# Generated by Django 4.1.2 on 2022-10-25 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=400, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(blank=True, max_length=10, null=True)),
                ('account_no', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('account_type', models.CharField(blank=True, choices=[(0, 'CURRENT'), (1, 'SAVINGS')], max_length=40, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_customer', to='accounts.customer')),
            ],
        ),
    ]
