# Generated by Django 4.1.2 on 2022-10-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customer_pincode_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='pincode',
            new_name='pin',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='amount',
            new_name='cid',
        ),
        migrations.RemoveField(
            model_name='account',
            name='cid',
        ),
    ]
